### ISSUE TITLE
Pass coordinates of all team players

### ISSUE THREAD

**Issue by Adman** [RoboCupJuniorTC/webots-soccer-sim-playground#12]
What about passing x, y and orientation of the robot to other robot within the same team (or maybe even of all robots)? Teams could incorporate some tactics.

**Comment by mrshu** [comment]
@Adman I believe this is what's already taking place -- the message the robot's controller currently gets actually contains positions of all robots, as well as the ball (see below). 

https://github.com/RoboCupJuniorTC/webots-soccer-sim-playground/blob/master/controllers/rcj_soccer_player/rcj_soccer_player.py#L11-L29

As such, I believe we can close this but feel free to reopen the issue if you feel like I did not address it fully.

Thanks!
