### ISSUE TITLE
Respawn when a robot turned over

### ISSUE THREAD

**Issue by aquahika** [RoboCupJuniorTC/webots-soccer-sim-playground#18]
When a robot turn/flip over and cannot move never again, respawn it

**Comment by aquahika** [comment]
Similar to #16, however, this probably requires to respawn immmidiatly?

**Comment by mrshu** [comment]
I guess  for our current purposes this is probably the very same thing as #16 -- in the future we can easily make the restart immediate.

**Comment by mrshu** [comment]
In the interest of doing the absolute minimum for the simulator to be of some use (i.e. Minimum Viable Simulator), I believe we can close this and let the lack of progress rule take care of it.

We can revisit it anytime afterwards, if it ends up being a serious problem.
